In [1]:
import numpy as np
import pandas as pd

In [3]:
# Exercise 1
arr1 = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr1)

Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# Exercise 2
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]  # 5th to 15th index
print("\nExercise 2:\n", extracted_elements)


Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [7]:
# Exercise 3
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series['pears'] = 4
print("\nExercise 3:\n", series)


Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [11]:
# Exercise 4
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 35, 40, 29, 31, 28, 33, 27],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("\nExercise 4:\n", df)


Exercise 4:
       name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   35      M
4     Emma   40      F
5    Frank   29      M
6    Grace   31      F
7   Hannah   28      F
8      Ian   33      M
9     Jack   27      M


In [13]:
# Exercise 5
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("\nExercise 5:\n", df)


Exercise 5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4     Emma   40      F     Manager
5    Frank   29      M     Analyst
6    Grace   31      F  Programmer
7   Hannah   28      F     Manager
8      Ian   33      M     Analyst
9     Jack   27      M  Programmer


In [15]:
# Exercise 6
age_filtered_df = df[df['age'] >= 30]
print("\nExercise 6:\n", age_filtered_df)


Exercise 6:
     name  age gender  occupation
1    Bob   30      M     Manager
3  David   35      M  Programmer
4   Emma   40      F     Manager
6  Grace   31      F  Programmer
8    Ian   33      M     Analyst


In [17]:
# Exercise 7
csv_filename = "dataframe.csv"
df.to_csv(csv_filename, index=False)  # Save to CSV
loaded_df = pd.read_csv(csv_filename)  # Read from CSV
print("\nExercise 7:\n", loaded_df)


Exercise 7:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   35      M  Programmer
4     Emma   40      F     Manager
5    Frank   29      M     Analyst
6    Grace   31      F  Programmer
7   Hannah   28      F     Manager
8      Ian   33      M     Analyst
9     Jack   27      M  Programmer
